sudo: required

language: ruby

services:
  - docker

before_install:
  - docker pull nubisproject/nubis-travis:master

script:
  - docker run --mount type=bind,source="$(pwd)",target=/nubis/files nubisproject/nubis-travis:master

notifications:
  slack:
    secure: EcMCXMa9u8TDDM9R0/R+ZRWJwo2Or/nJQC1rinzSLRc6hragI/WCPCoJqlOTLhG45G9WbWoGrbHYKgc3AwAMRl3xNoMj4tjVHw2aDWKzFYJK8rQBhpB8vtH8IedFkrXHu+Yv71ROAHBBowztKT9+xEnK7TRIO3ne3UL3XkUahpn7Wt6wAnKf+FuW1TY81M3vRGLKeavurE7kb4EurANMNyHRzg2JgxT6RDg9mofeUoRgjr9wfbDOIxwjou9+6q4pyDApMAxXZdAi/bWVilwz6Jt0t8WA+uv4oGJwT53rf1l15ZhNJKNo6bEbXOkm+RjRSni9PEs36GW/D2eEZros+VJamgMEWp1+Prb14org4vYH5E5uCpIulwiESk1f9FzbTejMnuOW224bS1TNrhWKgg5F03Mpd9OKAaynQ5ih6fFTfotMyYKG4BVqJUaM/A82WQ/3x2CHTY2dubH6+j8YDPA4X8BIqUHpEp2fDospdD+XnArasSDFZyWOsJxxhnTMxdOWDXkMvzQ0bVsIlDxDBpOE4mjhI3/ZaiTzv/h0mDSGrgX+kKqve2vkTj6j1/EFdhDqe/oyHE5g6XjA2B/58slp/2eM1tX2V6ZfhIoLbexKeehRiznkVax0BrJgWcdkLQri6XZJROJG8WrbWEo9kuyXxPa2297TgwOadaExIUg=
