#!/bin/bash

bro_user=bro
my_hostname=$(hostname)

sed -i -e "s/%%HOSTNAME%%/$my_hostname/g" /opt/bro/etc/node.cfg

# Should probably figure out a better way of doing this here
aws s3 cp s3://nsm-data/heka.toml /etc/heka.toml

su - ${bro_user} -c "/usr/local/sbin/nsmdataupdate.sh"
su - ${bro_user} -c "/usr/local/sbin/nsmconfigsupdate.sh"

su - ${bro_user} -c "/opt/bro/bin/broctl install"
su - ${bro_user} -c "/opt/bro/bin/broctl deploy"
su - ${bro_user} -c "/opt/bro/bin/broctl restart"

/etc/init.d/hekad start
#/etc/init.d/nsm start
